import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mes recettes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
